# Generated by Django 5.1.7 on 2025-03-20 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lesson', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courseschedule',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.course'),
        ),
        migrations.AddField(
            model_name='examseatingarrangement',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.classroom'),
        ),
        migrations.AddField(
            model_name='examseatingarrangement',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.examschedule'),
        ),
        migrations.AddField(
            model_name='instructorschedule',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.classroom'),
        ),
        migrations.AddField(
            model_name='instructorschedule',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.course'),
        ),
        migrations.AddField(
            model_name='instructorschedule',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invigilatorassignment',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.examschedule'),
        ),
        migrations.AddField(
            model_name='invigilatorassignment',
            name='invigilator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
